### ISSUE TITLE
Feature: User can view a map

### ISSUE THREAD

**Issue by PaulGlorioso** [PaulGlorioso/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to view a map that would eventually be filled with markers indicating the location of different trails.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user starts on a landing page which has a button that will lead to the map page. From that map page, they can pan around and view markers with information on a trail.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-02-15 154318](https://user-images.githubusercontent.com/93615301/154171458-eb4bfb1c-729c-46c5-84ac-b9bcaef94e88.jpg)
![Screenshot 2022-02-15 154329](https://user-images.githubusercontent.com/93615301/154171461-7451c012-3070-4b08-959e-6c46a7c3276c.jpg)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Set up package.json with proper dependencies and other devDependencies
- [x] install the react-google-maps/api using npm install
- [x] Create a component file to house google map feature.
- [x] Add google maps api key to env for easier access.
- [x] Set up react-google-maps-api useLoadScript hook
- [x] Set up a variable for the google maps libraries
- [x] With map component, create a function that initiates a map to render.
- [x] Set up map container to fit map size
- [x] Create a variable for center point for map to load at
- [x] Pull from the useLoadScript hook the variables isLoaded and loadError for when 
- [x] If a loadError occurs, return 'Error loading map'
- [x] If the map is still loading, return 'Loading map'
- [x] Return a div that has the GoogleMap class tag inside
- [x] Within that class, set up the properties for the map container, zoom, and center with the values set to the matching variables.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
