### ISSUE TITLE
Feature: User has access to nav bar through app

### ISSUE THREAD

**Issue by PaulGlorioso** [PaulGlorioso/final-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to click a button that will open and close a navbar that pops out from the side. On that navbar are links that will eventually lead to other parts of the app

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click on an icon which will allow a navbar to popout from the side giving the user access to links that will access other parts of the app

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-02-15 153854](https://user-images.githubusercontent.com/93615301/154337845-20a7952d-61e8-485e-b107-047cf4a9fc6c.jpg)
![Screenshot 2022-02-15 154329](https://user-images.githubusercontent.com/93615301/154337860-3dcbcec1-5236-4d21-adee-af5f530ce29e.jpg)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component file to house my navbar
- [x] Set up jsx for nav bar
- [x] Add anchors with temporarily broken links
- [x] Set up CSS for nav bar to open and close

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
