### ISSUE TITLE
Feature: User can create new Markers on the map

### ISSUE THREAD

**Issue by PaulGlorioso** [PaulGlorioso/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Set state up in map component using useState with the variables, markers and setMarkers with an empty array
- [x] On the onclick, create a new const called onMapClick
- [x] For onMapClick, call useCallback method and in method, call setMarkers recieving the current state and return the current markers in the array adding on a new marker object with the properties of lat, lng, and the locationId.
- [x] Create a counter variable and let it be 0
- [x] For the value of lat, set it to event.latLng.lat().
- [x] For the value of lng, set it to event.latLng.lng().
- [x] For the locationId, set it to the counter and increment it
- [x] Within the GoogleMap tags, call map on the markers where for each marker, it is returning a new Marker tag with the key set to the marker locationId, and the position set for lat on marker.lat, and lng on marker.lng

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
